name: Drobot
favicon: null
layout_spectrum: 0.29143494553864
typography_spectrum: 0.4870170005597174
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9564856218639761
  lightness: 0.503235244192183
  saturation: 0.5877228928729892
  rhythmicContrast: 0.7801445366349071
purpose: []
